version: '3'

services:
  mymongodb:
    build:
      dockerfile: Dockerfile
      context: ./mongodb
    networks:
      - shoppers
    restart: always

  mynodejsapp:
    depends_on:
      - mymongodb
    build:
      dockerfile: Dockerfile
      context: ./nodejs
    networks:
      - shoppers
    ports:
      - 8000:8000
    environment:
      DATABASE_USER: admin
      DATABASE_PASSWORD: 1111
      DATABASE_HOST: mymongodb
    restart: always

  myreactapp:
    depends_on:
      - mymongodb
      - mynodejsapp
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    networks:
      - shoppers
    restart: always
    ports:
      - 3000:80

networks:
  shoppers:
